version: 0.0
os: linux

files:
  - source: target
    destination: /tmp/srv/

permissions:
  - object: /tmp/srv/
    pattern: "*.jar"
    owner: ec2-user
    group: ec2-user

hooks:
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 20
      runas: ec2-user
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 20
      runas: ec2-user
